scripts/stackstorm.js

This is a temporary work-around until our pull request gets merged.
The difference between our and upstream `sendMessage` method is that we also send `parse` attribute letting slack API know to not parse and format the message.

Monkey patch slack-client sendMessage method

---

lib/st2_command_factory.js
package.json
scripts/stackstorm.js
tests/dummy-robot.js
tests/fixtures/aliases.json
tests/test-st2-command-factory.js

* A format like google {{query}} {{count=10}} will not work for the following command literals
1. google stackstorm
2. google stackstorm 7
3. google stackstorm count=5

[RFR] Modify format regex to allow for defaults

---

lib/utils.js
scripts/stackstorm.js
tests/test-utils.js

Previously, if the api or auth URL didn't contain a port, a default port (80 for https and 443) was not correctly propagated which meant the requests wouldn't work (they would time out).

Fix a default port propagation bug

---

package.json

Getting warn:
```sh
npm WARN engine hubot-stackstorm@0.1.1: wanted: {"node":"0.10.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
```
Is the only required node version `0.10.x` or we can extend it to `>= 0.10.x`?
See: 
https://github.com/github/hubot/blob/master/package.json#L34
https://github.com/github/generator-hubot/blob/master/package.json#L14
https://github.com/yeoman/yo/blob/master/package.json#L10

Don't hardcode node version

---

scripts/stackstorm.js

Taking advantage of ```robot.adapterName``` to provide compatibility with Hipchat. Modifies the message to not add the ```basic``` format (which I guess gets properly displayed in Slack) and also modifies the channel to send to, so the results appear properly (on hipchat the channel real name is BOTJID_CHANNELNAME@conf.hipchat.com)
Tested and can see the result of actions asked in the proper channel.
@Kami ?

Support Hipchat channel type and message format

---

lib/st2_authenticate.js
package.json
scripts/stackstorm.js
tests/test-st2-authenticate.js
tests/test-st2bot-setup.js
tests/test-utils.js

* With this change the authentication code is moved into a separate module. The modularization helps testability and also keep stackstorm.js sane.
* Added test cases for authentication and while working on tests cleaned up some previous tests also and/or fixed broken tests.
* Authentication is now a little resilient at bootstrap i.e. wait for the service to initialize before giving up.
* Failure to authenticate will no longer cause hubot to exit. An error is logged and hubot continues to work - this is to support deployments on existing hubot installs which seems like a common deployment pattern.

Break out auth in its owns module

---

tests/test-st2bot-setup.js

* Enabling auth for these test because the right environment variables
were setup lead to test failures. In order to make the test environment
agnostic explicitly disable the env vars.

For test-st2bot-setup disable auth

---

lib/format_data.js
lib/utils.js
package.json
scripts/stackstorm.js
tests/dummy-robot.js
tests/test-formatdata.js
tests/test-st2bot-setup.js

Large PR with many different changes. Which got inter-mingled with each other and I lost patience to detangle the mess.
* Moved all adapter specific code into specific modules
* Dropped all tableformat and jsonformat code since it is not used anyway
* Move recipient formatting to format module as well so that adapter specific is hidden away
* Truncate message text at 500 characters. (value is configurable via environment variables)
* Hardcode the right hipchat domain.
* Slack replace \u0022 with \u201c when it notices a left quote mark. This breaks
the command parsing on the back end. So something like run local "uanme -a" would
not work. Normalizing brings back the functionality in slack. Ofcourse the
downside to the approach is if a user legitemately would like to use left double
quote …

Refactor formatter

---

scripts/stackstorm.js
tests/test-utils.js

If user doesn't want to wait on the periodic commands reload they can now also send `SIGUSR2` signal to the bot process which will cause it to reload the commands without a restart.

Reload available commands on SIGUSR2 signal

---

README.md

Was surprised to see that messages are truncated now.
BTW, are you sure they should be truncated to `500` by default?
Personally I would always set it to `0` for no limit. Feel like it should be default behavior with optional possibility to cut those messages.
Especially because there wasn't such limit before.

Document ST2_MAX_MESSAGE_LENGTH

---

CHANGELOG.rst
package.json
scripts/stackstorm.js

Previously, if an exception was thrown (e.g. connection refused - API is offline, connection timeout, etc.). we wouldn't correctly log the reason for the loading failure (the error would just say null).

Better error reporting if we fail to load the commands because of an exception

---

lib/command_factory.js
tests/fixtures/aliases.json
tests/test-command-factory.js

cancel the previous pull request.  This one updates the test fixtures with a new test for the case when two formats match at the beginning.  e.g
alias4 fmt1 value1
alias4 fmt1 value2 word value2

fixed regex on command factory w/tests

---

lib/format_data.js
tests/test-formatdata.js

* Lets blame this on my lack of javascript foo. Didn't realize global replace was not.
FWIW, an API that does not be default go with global replace seem weird to me.

global replace in a string

---

lib/command_factory.js
tests/fixtures/aliases.json
tests/test-command-factory.js

* Commands literals with quoted parameters allow blank spaces. Support
for blank spaces added by delicately modifying the regexes.
Note : the ordering change in alias fixture is to require the more restrictive format to be placed higher.

Support white space

---

scripts/stackstorm.js

My chat ops returns are quite big so I wanted to have the results in the attachment.
It turns red for failures and there's the link to execution details.
I want to also change the initial message when an alias  is executed, let me know what you think

Use slack attachment to display results

---

README.md
scripts/stackstorm.js

Added options for the slack attachement colors and I put back the username in the message

Option for the colors and putting back the username when not a whisper

---

lib/format_data.js
lib/post_data.js
package.json
scripts/stackstorm.js
tests/test-formatdata.js
tests/test-postdata.js

* Also tests now since it can be unit tested
* Truncation of messages posted to slack is no longer necessary.
Validated changes with `slack` and `hipchat`. Looks like all the basic stuff is still working fine after my change.

Refactor message format into adapter specific classes

---

lib/command_factory.js
scripts/stackstorm.js

1. `\S` instead of `\w` to work with keys with `-` in them (closes #52).
2. `[\s\S]` instead of `.` to work with multiline matches.
3. More relaxed with whitespace inside brackets and around the equal sign for default params.

More relaxed command matching in Hubot

---

lib/command_factory.js
scripts/stackstorm.js

1. `aliases` don't get registered in Hubot's help.
2. `ack` configures the acknowledgement message: formatting and enabling/disabling.
3. `result` configures the result message: formatting and enabling/disabling.
4. The new regex from `chatops/regex` is also merged here.

Adding support for new ChatOps parameters

---

scripts/stackstorm.js

Supports the new object format passed by AliasExecution API (https://github.com/StackStorm/st2/pull/2229).
1. Correctly gets the execution id from context.
2. Uses actionalias from the API.
3. If `message` (jinja-formatted string) is specified, uses it.
4. If there’s no `message`, reverts to the standard format (with fun and all that).
5. Extra Firefly reference for bonus points from @jfryman.

New ack formatting

---

scripts/stackstorm.js

Moved disabling of the result output to the back-end, because `hubot-stackstorm` shouldn’t be concerned with this.

Revert ignoring of empty messages

---

lib/command_factory.js
lib/utils.js
scripts/stackstorm.js

Overlooked this one: when a format string is specified as a “display+representation” object, display is help-exclusive so it shouldn’t be matched as a command.

Exclude help entries from regex map

---

lib/command_factory.js

Converting spaces before and after arguments to `\s` for better multiline support.

Better multiline support

---

lib/utils.js

`::` is too widely used—including config files—and could behave badly when outputting gists.

A less common separator

---

lib/command_factory.js

Due to how hubot-help is implemented, it automatically replaces every mention of 'hubot' with bot alias.
I personally think this was a bad idea on hubot's part and it seems especially awful in our case, but we've decided to follow this convention for the time being instead of re-implementing help module.

Tweak help generation

---

lib/post_data.js
scripts/stackstorm.js

Fixes: #79 
What this adds: 
* Delimiter support for text vs code for hipchat messages.
* Ability to ping users via their hipchat mention_name (user.name does not ping a user)
* Ability to have chatops functions recognize hipchat private messages and respond in the correct manner
How this was tested: 
Forked docker-hubot
Updated package.json to "hubot-stackstorm"  : "git+https://github.com/charlottestjohn/hubot-stackstorm#hipchat-postdata",
sudo docker build -t charlottetestingstuff . (inside of the docker-hubot directory, in the vagrant)
sudo vi /etc/init.d/docker-hubot
change line 71 from "stackstorm/hubot" to "charlottetestingstuff"
sudo /etc/init.d/docker-hubot restart
:cookie: Ran command w/ {~} at the end of alias notify block from chat room, verified I was pinged in the room & that …

Hipchat postdata

---

lib/post_data.js
scripts/stackstorm.js

This makes st2 support Yammer through the `hubot-yammer` module. A bot can join pre-defined groups, and reply to new messages as well as comments.
`hubot-yammer` doesn’t support PMs though, so you can’t chat with the bot, and that’s kinda sad, but rooms should be enough for most uses. After all, you can create a private room for a bot.
Since we don’t have Yammer in the installer, a (very simple) manual modification of the `docker-hubot` init script would be required, so we can consider this experimental for now.
Also see https://github.com/StackStorm/docker-hubot/pull/6

Yammer handler and support for Yammer user/message objects

---

lib/post_data.js

This commit allows specifying a color for the Slack "attachment". It falls back on the old logic if no color is specified with the message.

Allow specifying color for Slack messages

---

lib/post_data.js
tests/test-postdata.js

with receiving slack messages thru weechat I was receiving -- NO FALLBACK DEFINED
defined the fallback to use the default text

added a fallback

---

lib/command_factory.js
package.json

Fixes #92
There was a bug in command matching that would match a valid command preceded by any text (i.e. `aaast2 list actions` would match `st2 list actions`). Parser on the back-end doesn’t have this issue, so it receives the command, can’t match any parameters and executes it with defaults.
This PR makes hubot only match the full string as it should.

Changing the regex to match the full command line

---

lib/command_factory.js

Fixes #94
There’s a bug that makes a `display` string, which is meant solely for
appearing in Hubot’s help, to go through the same transformations as
normal commands, which means it will be converted to a regex. It’s not
just unnecessary, but actually causes an error in some cases.

Avoid calling `getRegexForFormatString` for `display` parameters

---

lib/command_factory.js

In some cases with `display/representation` aliases help entries might
duplicate. This is a simple fix checking if the entry is already in the
array.

Hotfix: avoid duplicating help entries

---

lib/command_factory.js
scripts/stackstorm.js

As planned originally, commands are now matched in a case-insensitive
way; it’s achieved with the `i` flag instead of converting to
lowercase, because the latter is error-prone.
Fixes https://github.com/StackStorm/st2/issues/2566

Match commands ignoring case

---

lib/post_data.js

Add support for a few `extra` parameters:
1. `color` will set the attachment color in Slack.
2. `slack` object will be passed to `attachment.emit` as is, so it can be populated according to the attachment docs at https://api.slack.com/docs/attachments
It degrades gracefully: if there’s no `extra`, no additional parameters are added. If there’s a different adapter, no additional processing takes place.
This is supposed to go together with https://github.com/StackStorm/st2/pull/2572, but can be merged earlier.

Support `extra:color` and `extra:slack`

---

lib/format_data.js
lib/post_data.js
lib/utils.js
package.json
scripts/stackstorm.js
tests/fixtures/aliases.json
tests/test-2fa.js
tests/test-st2bot-setup.js
tests/test-twofactor.js

Goes together with https://github.com/StackStorm/st2contrib/pull/444.
This PR adds native support for two-factor auth through the Duo pack. Support can be enabled by setting `HUBOT_2FA` environment variable and having `extra:security:twofactor` flag in an alias. 
It works through “freezing” an execution attempt until a `2fa` announcement for a successful auth with the correspondent ID is caught in the stream.
The change is fully backwards-compatible; later I’ll add the env variable (commented out) to `st2chatops.env`, thoroughly documenting the case as well.

[RFR] Native support for two-factor auth

---

lib/utils.js
scripts/stackstorm.js

Error messages that Hubot posts on incorrect executions (the most common case is schema validation error in an alias) were previously sent to chat as plaintext, which is messy since the messages tend to get quite long. 
This PR makes those messages go through the same formatting process as our usual result messages do: e.g. in Slack it would result in prettified and truncated attachment with a red-colored strip.
Thanks to @Kami for ranting about this convincingly enough. 😛

Prettify error messages on incorrect executions

---

lib/post_data.js
tests/test-postdata.js

Fixes #108.
As reported by @jmound, long attachments (over 8000 characters long to be precise) are cut by Slack without an error or exception, so we have to catch those and split into multiple separate attachments. I couldn’t find a reference to this behavior in Slack docs, but could find workarounds in other’s Slack-involving code, so it’s seems to be a common method of dealing with the problem.
Long plaintext messages are split by Slack automatically.
Extra formatting (colors, etc.) is added to every chunk. 
Plaintext (where present) is only added to the first chunk.

Separate long Slack attachment into chunks

---

.travis.yml
package.json

Playing with ChatOps, it didn't work on node.js `0.10.x`.
So it's good to state that clearly in `package.json`.

Fix node Version

---

package.json
scripts/stackstorm.js

Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …

Update uuid to version 3.0.0

---

CHANGELOG.rst
lib/post_data.js
package.json
tests/dummy-adapters.js
tests/test-formatdata.js
tests/test-postdata.js

Based on https://github.com/slackapi/hubot-slack/pull/355/files#diff-04c6e90faac2675aa89e2176d2eec7d8R86 and https://api.slack.com/methods/chat.postMessage#formatting
Also closes #121

Slack post data should use new chat postMessage API

---

.travis.yml
CHANGELOG.rst
README.md
package.json
scripts/stackstorm.js

Solves #143 
- `st2client.js` needs to be updated since 0.4.3 does not support specifying stream url
- Use `utils.parseUrl()` just like `ST2_AUTH_URL` do, even the same logic is implemented in `st2client.js` ([here](https://github.com/StackStorm/st2client.js/blob/master/index.js#L50) and [here](https://github.com/StackStorm/st2client.js/blob/master/index.js#L63))
- We can just pass single string to `opts.auth` or `opts.stream` and let `st2client.js` handle URL parsing, but that is out of the scope here. If we want to do that, we should do it in separate PR.

Add ability to specify stream URL

---

CHANGELOG.rst
README.md
package.json
scripts/stackstorm.js

> This is spot during the K8s work https://github.com/StackStorm/st2-dockerfiles/pull/19
For consistency with other ENV variables (see https://docs.stackstorm.com/reference/cli.html#configuration), rename `ST2_API` -> `ST2_API_URL`.
The change still supports old `ST2_API` for backwards compatibility if someone is using `hubot-stackstorm` externally.
---
`st2chatops` change to `st2chatops.env` will come next.

Prefer 'ST2_API_URL' ENV instead of 'ST2_API' for consistency

---

lib/slack-messages.js
lib/slack_monkey_patch.js
package.json
scripts/stackstorm.js
tests/dummy-logger.js
tests/dummy-robot.js
tests/test-st2-invalid-auth.js

Final tweaks for #168. This should be merged into the `issue-124/exit_on_failures` branch before #168 is merged in. That PR is looking pretty good, but there were a lot of places we can/should refactor, and some places we absolutely needed to refactor so we can test the new changes.
This PR:
* Adds large comment in `slack_monkey_patch.js` for future developers to help determine if the monkey patching is still necessary.
* Removes `Object.assign()` polyfill from `lib/slack-messages.js` - **this requires node.js version > 8.3.0**
* Breaks out the dummy `Logger` out from `tests/dummy-robot.js` into its own module
* Add `robot_name` argument to dummy `Robot` mock, to better mirror actual `Robot` constructor
* Rename `api` and `client` variables (both `st2client.js` instances) to `api_client` …

Further tweaks for #168

---

CHANGELOG.rst
package.json
scripts/stackstorm.js

Fixes https://github.com/StackStorm/hubot-stackstorm/issues/158 
Setup `limit=-1` to retrieve all the action alias records.

Support pagination for action alias.

---

.travis.yml

Adds Node 11 and 12 to Travis tests, and allows them to fail without failing the build.
This is the first step to enabling support for those node versions.

Enable testing Node.js 11 and 12, but allow them to fail

---

CHANGELOG.rst
package.json
scripts/stackstorm.js
tests/test-st2-unauthorized.js

Addresses https://github.com/StackStorm/st2chatops/issues/124
Accidentally Closes #157
Accidentally Closes stackstorm/st2#4119
This bugfix solves particular problem when invalid, expired `ST2_API_KEY` / `ST2_AUTH_TOKEN` or any other `Unauthorized` response from st2 server leads to bot exit.
Previously the bot was running forever with no exit, trying to re-auth in a loop every `ST2_COMMANDS_RELOAD_INTERVAL` (2mins). Now we deem such errors as fatal.

 Exit hubot on Unauthorized errors

---

CHANGELOG.rst
package.json
scripts/stackstorm.js

Don't consider failed alias execution as a critical reason to exit hubot 

---

CHANGELOG.rst
package.json

Should help reduce the size of the diff of `npm-shrinkwrap.json` in https://github.com/StackStorm/st2chatops/pull/128.

Move babel-eslint to devDependencies instead of dependencies

---

CHANGELOG.rst
src/lib/adapters/mattermost.js
src/lib/adapters/msteams.js
src/lib/adapters/rocketchat.js
src/lib/adapters/slack-like.js
src/lib/adapters/slack.js
src/lib/adapters/spark.js

This PR is on top of #190.
This PR slightly refactors the adapter inheritance for Slack-like adapters.
It adds in an intermediary `SlackLikeAdapter` for the Slack-like providers. This should make it easier to use `DefaultAdapter` methods in subclasses, like with what is done in `SparkAdapter.formatData` and `SlackLikeAdapter.normalizeCommand`.
This makes things a bit easier:
```diff
-ThisAdapter.super_.prototype.customMethod.call(...)
+DefaultAdapter.customMethod(...)
```
I also removed the `normalizeAddressee` from the MS Teams adapter, since it was an override of [the same function from `DefaultAdapter`](https://github.com/StackStorm/hubot-stackstorm/blob/3a14cdd8ed73fb7f2c3647df215e02035065eebd/src/lib/adapters/default.js#L82) (and the MS Teams adapter inherits from `DefaultAdapter`). …

Redo adapter inheritance

---

CHANGELOG.rst
src/lib/adapters/mattermost.js
src/lib/slack-messages.js
test/dummy-adapters.js
test/test-postdata.js

This is the fix for the Mattermost adapter from [this forum post](https://forum.stackstorm.com/t/st2chatops-with-mattermost-not-replying/711/25).
I have tested this manually with a minimal Mattermost server in a VM.
The [`slack-attachment` event](https://github.com/loafoe/hubot-matteruser/blob/aa2814a6594183535fddff8503bde35576bbd4a5/src/matteruser.coffee#L84) was removed from the hubot-matteruser dependency in [PR 71](https://github.com/loafoe/hubot-matteruser/pull/71), but our Mattermost adapter did not get updated to avoid using that.
I switched over to using the [`send` method from hubot-matteruser](https://github.com/loafoe/hubot-matteruser/blob/master/src/matteruser.js#L205).
Note: That methods accepts two parameters: `envelope` and a variadic parameter `strings`, but contrary to …

Fix Mattermost adapter

---

CHANGELOG.rst
npm-shrinkwrap.json
package.json

I'm not 100% sure it's appropriate for a dependency like this should include an `npm-shrinkwrap.json` file, but this PR adds a production dependency lock file so projects that depend on this package don't install our devDependencies.
I also bumped the version number and add a changelog entry. Will push a release to NPM once this is reviewed and merged.
Will help StackStorm/st2chatops#135.
Commands:
```bash
rm -rf node_modules
npm install --production
npm shrinkwrap --production  # <-- MUST include --production
```

Add npm-shrinkwrap.json

---

CHANGELOG.rst
package-lock.json
package.json

This PR updates st2client.js from `1.1.3` to version `1.2.2`, so it pulls in the changes from PR StackStorm/st2client.js#76.

Update st2client.js to 1.2.2

---

CHANGELOG.rst
package-lock.json
package.json

PR #211 bumped the package version to 0.11.0 in `package-lock.json`, but PR #207 bumped the version to 0.11.0 in `package.json`. NPM already has version 0.11.0, so we need to bump to version 0.11.1 in both `package.json` and `package-lock.json` to push the new version to NPM.

Update version to 0.11.1

---

CHANGELOG.rst
package-lock.json
package.json
src/lib/adapters/slack-like.js
src/lib/adapters/slack.js
test/test-formatdata.js

copy/paste in slack proves problematic
because sometimes slack replaces a space
with the Latin1 non breaking space char /xA0
this cleans that up so that alias commands
and extra args can be appropriately recognized

Handle slack injected nbsp

---

package-lock.json
package.json

see if we can just do this minimal change like we were able to do in st2chatops

simplify the upgrade so we're backwards compatible
