StackStorm/hubot-stackstorm

- scripts/stackstorm.js
* original PR https://github.com/StackStorm/hubot-stanley/pull/27
> Recreate changes from hubot-stanley in new repo

- package.json
- scripts/stackstorm.js
- tests/test-st2bot-setup.js
* Added a mock adapter which is used to bootstrap the tests
* Trivial tests to validate setup functionality
> Hubot test with a mock adapter

- README.md
* Fix description and clarify meaning of ST2_CHANNEL
> Fix ST2_CHANNEL description.

- scripts/stackstorm.js
- tests/test-st2bot-setup.js
Fixes https://github.com/StackStorm/hubot-stackstorm/issues/12
> Preseve command case

- lib/st2_authenticate.js
* This prevents an unnecessary authenticate calls to back end APIs
> return from the resolve and reject paths

- lib/utils.js
- scripts/stackstorm.js
* If history_url is available use that else try to create a CLI command
string to generate the details.
> Best attempt to include execution details

- README.md
- scripts/stackstorm.js
- tests/test-st2bot-setup.js
Related: https://github.com/StackStorm/st2/pull/1817
> RFR: Rename notification channel to notification route.

- lib/command_factory.js
Extended matching to reflect edge cases on the back-end (combinations of mandatory and optional params, json/quoted values).
> Extended regexp

- scripts/stackstorm.js
Don’t post message if there’s no message body.
> Ignore empty messages

- lib/format_data.js
Fixes #2425
@StuartWhelan: I’m going to need a bit of help with testing if you don’t mind. Can you apply this PR to your instance and check if it works now?
> Use a different domain for HipChat Server

- selfcheck.sh
Some minor updates to make `shellcheck` a bit happier.
> Selfcheck lint

- scripts/stackstorm.js
* Precedence for auth mechanism is API_KEY, AUTH_TOKEN and username/password.
> Auth precedence

- scripts/stackstorm.js
Providing any one of auth_url, username and password causes failures.
> change username password validation

- lib/utils.js
- package.json
- scripts/stackstorm.js
- tests/test-utils.js
https://github.com/StackStorm/hubot-stackstorm/issues/120
https://github.com/StackStorm/st2/pull/2820
> Get history URL from execution model when present

- scripts/stackstorm.js
See https://github.com/StackStorm/st2client.js
> Include request ID in chatops err message for easier debugging

- README.md
> The tiniest typo fix

- lib/format_data.js
- lib/post_data.js
It's the second version of Mattermost support. In this version messages are split to 3800 characters (4000 maximum message length in Mattermost).
> mattermost support

- lib/post_data.js
Add support for sending file attachments via the extra dict to the spark adapter.
> add some support in the spark adapter to send extra dicts

- CHANGELOG.rst
- package.json
Release `hubot-stackstorm` v0.5.1 before next major (?) change in https://github.com/StackStorm/hubot-stackstorm/pull/138
> Release missed v0.5.1

- CHANGELOG.rst
- README.md
- lib/format_data.js
- lib/post_data.js
- package.json
- tests/test-formatdata.js
> Add rocketchat

- CHANGELOG.rst
- lib/post_data.js
**Based on the issue Support for "Button attachments" #151**
Inorder to accept the matteruser adapter message attachments we have changed the attachement json in post_data.js
> Button attachement fix for mattermostuser

- CHANGELOG.rst
Thanks to @armab for pointing this out.
> Add #147 to changelog

- lib/post_data.js
Rename function name from DefaultFormatter to DefaultDataPostHandler.
> Change the function name for more appropriate.

- CHANGELOG.rst
- package.json
Preparing for v0.10.0 release.
> Bump version to 0.10.0

- CHANGELOG.rst
- package-lock.json
- package.json
* Update `st2client` to 1.2.3
* Install `mversion` as a developer dependency so we can use it to bump versions in the future (like what the README says to do)
* Updated the changelog
* Bumped version to 0.10.4 with `mversion`
> Bump version to 0.10.4 (update st2client to 1.2.3)

- .travis.yml
- test/test-st2-invalid-auth.js
Update to check against node  > 12
> Update node checks
